# Generated by Django 5.1.6 on 2025-03-15 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('equipe', models.TextField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=100)),
                ('status_projeto', models.CharField(choices=[('finalizado', 'Finalizado'), ('em_andamento', 'Em andamento'), ('nao_finalizado', 'Não Finalizado'), ('cancelado', 'Cancelado')], default='em_andamento', max_length=20)),
                ('status_implantacao', models.CharField(choices=[('nao_implantado', 'Não Implantado'), ('implantado', 'Implantado')], default='nao_implantado', max_length=20)),
                ('status_registro', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='nao_iniciado', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
