# Generated by Django 5.1.6 on 2025-03-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='nome_abrevidado',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='nome_da_equipe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status_registro',
            field=models.CharField(choices=[('nao_registrado', 'Não Regristrado'), ('registro_andamento', 'Registro em Andamento'), ('registro_concluido', 'Registro Concluído')], default='nao_registrado', max_length=20),
        ),
    ]
