# Generated by Django 5.1.6 on 2025-03-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_projeto_nome_abrevidado_projeto_nome_da_equipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='nome_abrevidado',
            new_name='nome_abreviado',
        ),
    ]
