# Generated by Django 5.1.6 on 2025-03-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_rename_nome_abrevidado_projeto_nome_abreviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link_do_projeto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
