# Generated by Django 5.1.6 on 2025-03-18 01:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_projeto_link_do_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
